import { useEffect, useMemo, useRef, useState } from "react";
import { themeFromColorMapping } from "hello-wasm";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Separator } from "@/components/ui/separator";
import { Switch } from "@/components/ui/switch";
import { DEFAULT_MAPPING, DEFAULT_PALETTE, hexForRole, type Mapping, type PaletteColor, type SemanticRole } from "@/lib/palette";
import { applyTheme, type Theme } from "@/lib/theme";
import { MappingEditor } from "./MappingEditor";
import { PaletteEditor } from "./PaletteEditor";

function App() {
  const [palette, setPalette] = useState<PaletteColor[]>(DEFAULT_PALETTE);
  const [mapping, setMapping] = useState<Mapping>(DEFAULT_MAPPING);
  const [error, setError] = useState<string | null>(null);
  const previewRef = useRef<HTMLDivElement>(null);
  const nextColorId = useRef(1);

  const neutralHex = hexForRole(palette, mapping, "neutral");
  const accentHex = hexForRole(palette, mapping, "accent");

  const theme = useMemo<Theme | null>(() => {
    try {
      const t = themeFromColorMapping(neutralHex, accentHex) as Theme;
      setError(null);
      return t;
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
      return null;
    }
  }, [neutralHex, accentHex]);

  useEffect(() => {
    if (theme && previewRef.current) {
      applyTheme(previewRef.current, theme);
    }
  }, [theme]);

  function handleMappingChange(role: SemanticRole, colorName: string) {
    setMapping((m) => ({ ...m, [role]: colorName }));
  }

  function handleRename(index: number, name: string) {
    setPalette((p) => p.map((c, i) => (i === index ? { ...c, name } : c)));
  }

  function handleRecolor(index: number, hex: string) {
    setPalette((p) => p.map((c, i) => (i === index ? { ...c, hex } : c)));
  }

  function handleRemove(index: number) {
    setPalette((p) => {
      if (p.length <= 1) return p;
      const removed = p[index];
      const next = p.filter((_, i) => i !== index);
      const fallback = next[0]?.name ?? "";
      setMapping((m) => ({
        neutral: m.neutral === removed.name ? fallback : m.neutral,
        accent: m.accent === removed.name ? fallback : m.accent,
      }));
      return next;
    });
  }

  function handleAdd() {
    const name = `color-${nextColorId.current++}`;
    setPalette((p) => [...p, { name, hex: "#000000" }]);
  }

  return (
    <main className="mx-auto flex min-h-screen max-w-6xl flex-col gap-6 p-6 lg:flex-row">
      <div className="flex w-full flex-col gap-6 lg:w-96">
        <PaletteEditor
          palette={palette}
          onRename={handleRename}
          onRecolor={handleRecolor}
          onRemove={handleRemove}
          onAdd={handleAdd}
        />
        <MappingEditor palette={palette} mapping={mapping} onChange={handleMappingChange} />
        {error && <p className="text-xs text-destructive">{error}</p>}
      </div>

      <div
        ref={previewRef}
        data-testid="preview"
        className="flex w-full flex-1 items-start justify-center rounded-xl bg-background p-8 text-foreground ring-1 ring-border"
      >
        <Card className="w-full max-w-sm">
          <CardHeader>
            <div className="flex items-center justify-between">
              <CardTitle>Team settings</CardTitle>
              <Badge>Pro plan</Badge>
            </div>
            <CardDescription>
              These controls are styled entirely from the CSS variables generated by the
              editor on the left.
            </CardDescription>
          </CardHeader>
          <CardContent className="flex flex-col gap-4">
            <div className="flex flex-col gap-1.5">
              <Label htmlFor="team-name">Team name</Label>
              <Input id="team-name" defaultValue="Design Systems" />
            </div>

            <Separator />

            <div className="flex items-center justify-between gap-2">
              <Label htmlFor="email-notifications" className="flex-col items-start gap-0.5">
                Email notifications
                <span className="font-normal text-muted-foreground">
                  Get notified when tokens change
                </span>
              </Label>
              <Switch id="email-notifications" defaultSelected />
            </div>
          </CardContent>
          <CardFooter className="flex-col items-stretch gap-2 border-t pt-4">
            <div className="flex gap-2">
              <Button variant="outline" className="flex-1">
                Cancel
              </Button>
              <Button className="flex-1">Save changes</Button>
            </div>
            <Button variant="destructive" className="w-full">
              Delete team
            </Button>
          </CardFooter>
        </Card>
      </div>
    </main>
  );
}

export default App;
