import { useEffect, useMemo, useRef, useState } from "react";
import { themeFromColorMapping } from "hello-wasm";
import { FormProvider, useWatch } from "react-hook-form";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Separator } from "@/components/ui/separator";
import { Switch } from "@/components/ui/switch";
import { useZodForm } from "@/lib/insane-forms";
import { DEFAULT_MAPPING, DEFAULT_PALETTE, hexForRole, type Mapping, type PaletteColor, type SemanticRole } from "@/lib/palette";
import { applyTheme, type Theme } from "@/lib/theme";
import { MappingEditor } from "./MappingEditor";
import { PaletteEditor } from "./PaletteEditor";
import { PaletteFormSchema } from "./palette-form";

function App() {
  const form = useZodForm(PaletteFormSchema, {
    defaults: { colors: DEFAULT_PALETTE },
    mode: "onChange",
  });
  const watchedColors = useWatch({ control: form.control, name: "colors" }) as unknown as
    | PaletteColor[]
    | undefined;
  const colors = watchedColors ?? DEFAULT_PALETTE;

  const [mapping, setMapping] = useState<Mapping>(DEFAULT_MAPPING);
  const [error, setError] = useState<string | null>(null);
  const previewRef = useRef<HTMLDivElement>(null);

  // A mapped color may be removed or renamed out from under its role — fall
  // back to the first remaining color when that happens.
  useEffect(() => {
    const names = new Set(colors.map((c) => c.name));
    setMapping((m) => {
      const fallback = colors[0]?.name ?? "";
      const neutral = names.has(m.neutral) ? m.neutral : fallback;
      const accent = names.has(m.accent) ? m.accent : fallback;
      return neutral === m.neutral && accent === m.accent ? m : { neutral, accent };
    });
  }, [colors]);

  const neutralHex = hexForRole(colors, mapping, "neutral");
  const accentHex = hexForRole(colors, mapping, "accent");

  const theme = useMemo<Theme | null>(() => {
    try {
      const t = themeFromColorMapping(neutralHex, accentHex) as Theme;
      setError(null);
      return t;
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
      return null;
    }
  }, [neutralHex, accentHex]);

  useEffect(() => {
    if (theme && previewRef.current) {
      applyTheme(previewRef.current, theme);
    }
  }, [theme]);

  function handleMappingChange(role: SemanticRole, colorName: string) {
    setMapping((m) => ({ ...m, [role]: colorName }));
  }

  return (
    <main className="mx-auto flex min-h-screen max-w-6xl flex-col gap-6 p-6 lg:flex-row">
      <div className="flex w-full flex-col gap-6 lg:w-96">
        <FormProvider {...form}>
          <form onSubmit={(event) => event.preventDefault()}>
            <PaletteEditor />
          </form>
        </FormProvider>
        <MappingEditor palette={colors} mapping={mapping} onChange={handleMappingChange} />
        {error && <p className="text-xs text-destructive">{error}</p>}
      </div>

      <div
        ref={previewRef}
        data-testid="preview"
        className="flex w-full flex-1 items-start justify-center rounded-xl bg-background p-8 text-foreground ring-1 ring-border"
      >
        <Card className="w-full max-w-sm">
          <CardHeader>
            <div className="flex items-center justify-between">
              <CardTitle>Team settings</CardTitle>
              <Badge>Pro plan</Badge>
            </div>
            <CardDescription>
              These controls are styled entirely from the CSS variables generated by the
              editor on the left.
            </CardDescription>
          </CardHeader>
          <CardContent className="flex flex-col gap-4">
            <div className="flex flex-col gap-1.5">
              <Label htmlFor="team-name">Team name</Label>
              <Input id="team-name" defaultValue="Design Systems" />
            </div>

            <Separator />

            <div className="flex items-center justify-between gap-2">
              <Label htmlFor="email-notifications" className="flex-col items-start gap-0.5">
                Email notifications
                <span className="font-normal text-muted-foreground">
                  Get notified when tokens change
                </span>
              </Label>
              <Switch id="email-notifications" defaultSelected />
            </div>
          </CardContent>
          <CardFooter className="flex-col items-stretch gap-2 border-t pt-4">
            <div className="flex gap-2">
              <Button variant="outline" className="flex-1">
                Cancel
              </Button>
              <Button className="flex-1">Save changes</Button>
            </div>
            <Button variant="destructive" className="w-full">
              Delete team
            </Button>
          </CardFooter>
        </Card>
      </div>
    </main>
  );
}

export default App;
