import { useEffect, useMemo, useRef, useState } from "react";
import { themeFromColorMapping } from "hello-wasm";
import { FormProvider, useWatch } from "react-hook-form";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { OsWindow } from "@/components/ui/os-window";
import { Separator } from "@/components/ui/separator";
import { Sidebar } from "@/components/ui/sidebar";
import { Switch } from "@/components/ui/switch";
import { useZodForm } from "@/lib/insane-forms";
import {
  ANSI_ROLES,
  DEFAULT_MAPPING,
  DEFAULT_PALETTE,
  DEFAULT_TOKEN_ROLES,
  hexForRole,
  type EditableRole,
  type Mapping,
  type PaletteColor,
  type SemanticRole,
} from "@/lib/palette";
import { applyTheme, type Theme } from "@/lib/theme";
import { ComponentShowcase } from "./ComponentShowcase";
import { MappingEditor } from "./MappingEditor";
import { PaletteEditor } from "./PaletteEditor";
import { PaletteFormSchema } from "./palette-form";
import { TerminalPreview } from "./TerminalPreview";
import { TokenRoleEditor } from "./TokenRoleEditor";

function App() {
  const form = useZodForm(PaletteFormSchema, {
    defaults: { colors: DEFAULT_PALETTE },
    mode: "onChange",
  });
  const watchedColors = useWatch({ control: form.control, name: "colors" }) as unknown as
    | PaletteColor[]
    | undefined;
  const colors = watchedColors ?? DEFAULT_PALETTE;

  const [tokenRoles, setTokenRoles] = useState<EditableRole[]>(DEFAULT_TOKEN_ROLES);
  const [mapping, setMapping] = useState<Mapping>(DEFAULT_MAPPING);
  const [darkMode, setDarkMode] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const previewRef = useRef<HTMLDivElement>(null);

  // A mapped color may be removed or renamed out from under its role — fall
  // back to the first remaining color when that happens.
  useEffect(() => {
    const names = new Set(colors.map((c) => c.name));
    setMapping((m) => {
      const fallback = colors[0]?.name ?? "";
      let changed = false;
      const next = { ...m };
      for (const role of Object.keys(next) as SemanticRole[]) {
        if (!names.has(next[role])) {
          next[role] = fallback;
          changed = true;
        }
      }
      return changed ? next : m;
    });
  }, [colors]);

  const neutralHex = hexForRole(colors, mapping, "neutral");
  const accentHex = hexForRole(colors, mapping, "accent");

  const theme = useMemo<Theme | null>(() => {
    try {
      const t = themeFromColorMapping(neutralHex, accentHex, darkMode) as Theme;
      setError(null);
      return t;
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
      return null;
    }
  }, [neutralHex, accentHex, darkMode]);

  useEffect(() => {
    if (theme && previewRef.current) {
      applyTheme(previewRef.current, theme);
    }
  }, [theme]);

  function handleMappingChange(role: SemanticRole, colorName: string) {
    setMapping((m) => ({ ...m, [role]: colorName }));
  }

  return (
    <main className="mx-auto flex min-h-screen max-w-[100rem] flex-col gap-6 p-6 lg:flex-row">
      <Sidebar>
        <FormProvider {...form}>
          <form onSubmit={(event) => event.preventDefault()}>
            <PaletteEditor />
          </form>
        </FormProvider>

        <Separator />

        <TokenRoleEditor
          roles={tokenRoles}
          onRolesChange={setTokenRoles}
          palette={colors}
          mapping={mapping}
          onMappingChange={handleMappingChange}
        />

        {error && <p className="text-xs text-destructive">{error}</p>}
      </Sidebar>

      <div className="flex w-full flex-1 flex-col items-center gap-6">
        <div className="flex w-full items-center justify-between">
          <h2 className="text-sm font-medium text-muted-foreground">Preview</h2>
          <div className="flex items-center gap-2">
            <Label htmlFor="dark-mode-toggle">Dark mode</Label>
            <Switch id="dark-mode-toggle" isSelected={darkMode} onChange={setDarkMode} />
          </div>
        </div>

        <div ref={previewRef} data-testid="preview" className="flex w-full flex-col gap-6">
          <OsWindow title="Team Settings" className="w-full">
            <div className="flex flex-col gap-4 bg-card py-4 text-sm text-card-foreground">
              <CardHeader>
                <div className="flex items-center justify-between">
                  <CardTitle>Team settings</CardTitle>
                  <Badge>Pro plan</Badge>
                </div>
                <CardDescription>
                  These controls are styled entirely from the CSS variables generated by the
                  editor on the left.
                </CardDescription>
              </CardHeader>
              <CardContent className="flex flex-col gap-4">
                <div className="flex flex-col gap-1.5">
                  <Label htmlFor="team-name">Team name</Label>
                  <Input id="team-name" defaultValue="Design Systems" />
                </div>

                <Separator />

                <div className="flex items-center justify-between gap-2">
                  <Label htmlFor="email-notifications" className="flex-col items-start gap-0.5">
                    Email notifications
                    <span className="font-normal text-muted-foreground">
                      Get notified when tokens change
                    </span>
                  </Label>
                  <Switch id="email-notifications" defaultSelected />
                </div>
              </CardContent>
              <CardFooter className="flex-col items-stretch gap-2 border-t pt-4">
                <div className="flex gap-2">
                  <Button variant="outline" className="flex-1">
                    Cancel
                  </Button>
                  <Button className="flex-1">Save changes</Button>
                </div>
                <Button variant="destructive" className="w-full">
                  Delete team
                </Button>
              </CardFooter>
            </div>
          </OsWindow>

          <ComponentShowcase />
        </div>

        <TerminalPreview palette={colors} mapping={mapping} />
      </div>

      <Sidebar>
        <MappingEditor
          title="Terminal colors (ANSI 16)"
          description="Map each ANSI slot to a palette color."
          roles={ANSI_ROLES}
          palette={colors}
          mapping={mapping}
          onChange={handleMappingChange}
        />
      </Sidebar>
    </main>
  );
}

export default App;
